Kubernetes 1 HW28
Otus-DevOps-2017-11/artemsurov_microservices pull request #11
Opened 2018-04-02 22:31 UTC by artemsurov

Прошел жестокий путь от Келси Хайтаура и законспектил часть жести  в README

2018-04-12 09:15 UTC, serjs requested changes
Привет!

По hard-way все ок, а вот deployment исправь к единому виду. У тебя местами в metadata просто comment (к примеру), а где-то post-pod. Приведи всю метадату к единому формату, к примеру post, comment, ui, можно ПР можно будет мержить

2018-04-12 09:38 UTC, artemsurov commented
Привет, @serjs !
Если я правильно понял место для правок, я внес изменения в metedata, добавив '-pod' к comment.

2018-04-17 05:16 UTC, merged

2018-05-13 20:19 UTC, artemsurov commented
@serjs Привет!
Погаси, пожалуйста, огонек на сайте Otus с этой домашкой)

2018-05-14 17:33 UTC, Nklya commented
Привет.
Отметил в табеле.

2018-05-14 17:36 UTC, artemsurov commented
Спасибо)