Kubernetes 3
Otus-DevOps-2017-11/artemsurov_microservices pull request #13
Opened 2018-04-08 21:21 UTC by artemsurov

Выполнил 30 домашнее задание, а именно основные пункты.
Единственное секьюрный ingress у меня так и не заработал, пришлось откатится к обычному.

2018-05-03 05:55 UTC, vitkhab requested changes
В целом, хорошо. Чисто выполненная работа. У меня получилось заставить приложение работать.

Для зачета нужно исправить:
- `storageClassName` в mongo-claim-dynamic.yml
- сетевую политику mongo-network-policy.yml
- выполнить работу с терминацией TLS трафика (слайды 42-45)

Я понимаю, что прошло много времени после сдачи ДЗ. Возможно будет сложно что-то вспомнить. Я готов тебе помочь, если будут вопросы - задавай

2018-05-03 05:55 UTC, vitkhab commented on kubernetes/mongo-claim-dynamic.yml
> +  storageClassName: slow
В конфигурации не описан storageClassName с именем "slow". MongoDB будет ожидать создания диска и никогда его не дождется. Зато в конфигурации описан другой класс, можно указать его.

В гисте была опечатка в этом месте. Тем не менее на слайдах презинтации - все указано правильно.

2018-05-03 05:55 UTC, vitkhab commented on kubernetes/mongo-network-policy.yml
> +          component: post
Неправильно применение правил сетевой политики.
Все правила описанные в `podSelector` должны выполниться, чтобы правило сработало, между условиями podSelector ставится операция логического _И_. То есть трафик разрешен только для подов со всеми Label'ами app=reddit, component=comment и component=post. В конфигурации таких подов нет.

Правила в рамках from отрабатываются до первого совпадения (работают так, если бы между ними стояла операция логического _ИЛИ_). То есть можно описать несколько `podSelector`

2018-05-03 05:55 UTC, vitkhab commented on kubernetes/ui-ingress.yml
> +  name: ui
Не выполнена работа с терминацией TLS траффика.

2018-05-04 06:59 UTC, artemsurov commented
Привет, @vitkhab! Спасибо за замечания, все поправил)

2018-05-05 11:11 UTC, vitkhab requested changes
С именем `storageClass` не угадал. Исправь, пожалуйста. В комментариях дал подсказку

2018-05-05 11:11 UTC, vitkhab commented on kubernetes/mongo-claim-dynamic.yml
> +  storageClassName: mongo-pvc
`storageClassName` указывается в поле `name` в описании `storageClass`
https://github.com/Otus-DevOps-2017-11/artemsurov_microservices/pull/13/files#diff-34903e97e63f4a35e8c07040b93b2f7bR5

2018-05-05 15:08 UTC, artemsurov commented
Даже стыдненько немного за ошибку, второпях правил(

2018-05-06 08:49 UTC, vitkhab approved these changes
Спасибо за исправления! Теперь все выглядит отлично. Можно мерждить

2018-05-06 10:40 UTC, merged