Monitoring 1
Otus-DevOps-2017-11/artemsurov_microservices pull request #7
Opened 2018-03-05 19:39 UTC by artemsurov

В данном дз выполнил основную часть и сделал одно задание со звездочкой, смог замониторить mongodb

2018-03-08 19:20 UTC, Nklya requested changes
Добрый вечер.

Артем, почти все выглядит ок.
Нужно пофиксить эти проблемы:
1. Вычистить build_info.txt и занести его в .gitignore
2. Вычистить .env, занести его в .gitignore, закоммитить рабочий .env.example

2018-03-08 19:20 UTC, Nklya commented on docker/.env
> +UIPORT=9292:9292
.env должен быть в .gitignore, этот нужно вычистить, в качестве примера нужно закоммитить .env.example.

Плюс, в .env нет переменной USERNAME. Откуда композ знает, какие образы использовать?

2018-03-08 19:20 UTC, Nklya commented on docker/docker-compose.yml
> +    command:
Либо можно передать адрес монги через переменную окружения

2018-03-08 19:20 UTC, Nklya commented on src/comment/build_info.txt
> +9ddc481
build_info.txt должны быть в .gitignore
Это нужно вычистить.

2018-03-08 19:20 UTC, Nklya commented on src/post-py/build_info.txt
> +9ddc481
build_info.txt должны быть в .gitignore
Это нужно вычистить.

2018-03-08 19:20 UTC, Nklya commented on src/ui/build_info.txt
> +9ddc481
build_info.txt должны быть в .gitignore
Это нужно вычистить.

2018-03-08 19:20 UTC, Nklya commented
25 ДЗ мержить пока нельзя, пока не будут смержены 21 и 23

2018-03-10 09:18 UTC, artemsurov commented on docker/docker-compose.yml
> +    command:
Эта так сделать надо или это просто предложение?)

2018-03-10 09:20 UTC, Nklya commented on docker/docker-compose.yml
> +    command:
Нет, это просто инфа.
Те пункты, которые нужно пофиксить выше

2018-03-10 09:35 UTC, artemsurov commented on docker/.env
> +UIPORT=9292:9292
я задавал USERNAME в переменные окружения) Сейчас добавил в env.example

2018-03-10 09:40 UTC, artemsurov commented
@Nklya Привет! Спасибо за замечания! Все поправил

2018-03-10 09:41 UTC, Nklya approved these changes
Да, теперь все ок 👍

2018-03-10 09:42 UTC, merged

2018-03-10 09:42 UTC, Nklya commented
Смержил для проверки дальше